shared:
  legacy:
    name: Legacy
    price: 99
    stripe_price_id: price_legacy_123
    revenue_cat_product_identifier: legacy_plan_rc_123
  part_time:
    name: Part-time
    price: 99
    stripe_price_id: price_part_time_456
    revenue_cat_product_identifier: part_time_plan_rc_456
  full_time:
    name: Full-time
    price: 299
    stripe_price_id: price_full_time_789
    revenue_cat_product_identifier: full_time_plan_rc_789
  free:
    name: Free
    price: 0
    stripe_price_id: free
    revenue_cat_product_identifier: free
